MVC/Controllers/CardController.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using MVC.ViewModels;
using Services;

namespace MVC.Controllers
{
    public class CardController : Controller
    {
       private readonly ProductManager _productManager;

        public CardController(ProductManager productManager)
        {
            _productManager = productManager;
        }

        public IActionResult Index()
        {
            var productIdList = Request.Cookies["cartItem"];
            List <Product> productList= null;
            CardVM VM = new();
            if (productIdList != null && productIdList!="")
            {
                List<int> productIds = productIdList.Split('-').Select(c => int.Parse(c)).ToList();
                 productList= _productManager.GetProductIds(productIds.Distinct());
                VM.ProductIds = productIds;
                VM.Products = productList;
            }

            return View(VM);
        }
    }
}

MVC/Controllers/OrderController.cs
using Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MVC.ViewModels;
using Services;

namespace MVC.Controllers
{
    public class OrderController : Controller
    {
        private readonly ProductManager _productManager;
        private readonly OrderManager _orderManager;
        private readonly UserManager<EcommerceUser> _userManager;

        public OrderController(UserManager<EcommerceUser> userManager, ProductManager productManager, OrderManager orderManager)
        {
            _userManager = userManager;
            _productManager = productManager;
            _orderManager = orderManager;
        }

        public async Task<IActionResult> CheckOut()
        {
            var productIdList = Request.Cookies["cartItem"];
            List<Product> productList = null;
            CheckoutVM VM = new();
            if (productIdList != null && productIdList != "")
            {
                List<int> productIds = productIdList.Split('-').Select(c => int.Parse(c)).ToList();
                productList = _productManager.GetProductIds(productIds.Distinct());
                VM.ProductIds = productIds;
                VM.Products = productList;
                var selectedUser = await _userManager.FindByIdAsync(User.Identity.Name);
                if (selectedUser!=null)
                {
                    VM.CustomerId = selectedUser.Id;
                    VM.CustomerName = selectedUser.UserName;
                    VM.CustomerEmail = selectedUser.Email;
                    VM.CustomerPhone = selectedUser.PhoneNumber;
                }
                return View(VM);

            }
            return View();
        }


        [HttpPost]
        public async Task<IActionResult>  CheckOut(CheckoutVM checkvm)
        {
            Order order = new Order();
            var productIdList = Request.Cookies["cartItem"];
            List<Product> productList = null;

            if(productIdList != null && productIdList != "")
            {
                List<int>productIds=productIdList.Split("-").Select(c=>int.Parse(c)).ToList();
                productList = _productManager.GetProductIds(productIds.Distinct());
                order.CustomerPhone = checkvm.CustomerPhone;
                order.CustomerEmail = checkvm.CustomerEmail;
                order.CustomerName = checkvm.CustomerName;
                order.CustomerId = checkvm.CustomerId;
                order.OrderCode = Guid.NewGuid(). ToString();
                order.PlacedOn = DateTime.Now;
                order.OrderDetails = new List<OrderDetail>();
                order.OrderDetails.AddRange(productList.Select(c => new OrderDetail()
                {
                    ProductId=c.Id,
                    Quantity=(ushort)productIds.Where(p=>p==c.Id).Count(),
                    ItemPrice=c.Price,
                    Id=order.Id,
                }));
                 _orderManager.AddOrder(order);
                Response.Cookies.Delete("cartItem");
            }
            return View();
        }
        
    }
}

MVC/Controllers/ProductController.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using MVC.ViewModels;
using Services;

namespace MVC.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductManager _productManager;
        private readonly CategoryManager _categoryManager;

        public ProductController(ProductManager productManager, CategoryManager categoryManager)
        {
            _productManager = productManager;
            _categoryManager = categoryManager;
        }

        public IActionResult Details(int? id)
        {
            if(id == null) return NotFound();
            var singleProduct = _productManager.GetProductId(id);
            var findProduct = _productManager.GetProductId(id);

            if (singleProduct == null) return NotFound();
            SingleProductVM sp = new SingleProductVM()
            {
                Product = singleProduct,
                Products = _productManager.GetAllProduct(),
                Categorys = _categoryManager.GetAll(),
                sameProducts=_productManager.FindCategory(findProduct.CategoryID,id.Value)
            };
            return View(sp);
        }
    }
}

MVC/Views/Card/Index.cshtml
@model CardVM
@{
    ViewData["Title"]="Card Index";
}
<style>
    .itemName{
        font-size:15px;
        
    }
    .ths{
        text-align:center;
    }
  .cart-plus-minus {
  border: 2px solid;
  height: 45px;
  line-height: 38px;
  width: 140px;
  text-align: center; }

.qtybutton {
  height: 100%;
  width: 30%; }

.dec.qtybutton {
  float: left;
  border-right: 2px solid; }

.inc.qtybutton {
  float: right;
  border-left: 2px solid; }

.cart-plus-minus,
.dec.qtybutton,
.inc.qtybutton {
    cursor:pointer;
  background-color: var(--white);
  border-color: var(--border-color-11);
  font-size: 20px;
  font-weight: 700; }

input.cart-plus-minus-box {
  background: transparent none repeat scroll 0 0;
  -webkit-box-shadow: none;
  box-shadow: none;
  border: none;
  height: 100%;
  margin-bottom: 0;
  padding: 0;
  text-align: center;
  width: 40%;
  font-weight: 700;
  font-family: var(--ltn__heading-font); }
</style>
    <!-- BREADCRUMB AREA START -->
    <div class="ltn__breadcrumb-area ltn__breadcrumb-area-4 bg-overlay-theme-10--- bg-image" data-bg="Assets/img/bg/4.png">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ltn__breadcrumb-inner ltn__breadcrumb-inner-4 justify-content-between">
                        <div class="section-title-area">
                            <h1 class="section-title white-color">Cart</h1>
                        </div>
                        <div class="ltn__breadcrumb-list">
                            <ul>
                                <li><a href="index.html">Home</a></li>
                                <li>Cart</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- BREADCRUMB AREA END -->

    <!-- SHOPING CART AREA START -->
    <div class=" carts cart-area liton__shoping-cart-area mb-120">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 my-cart-area">
                  @if(Model !=null && Model.Products!=null && Model.ProductIds !=null && Model.ProductIds.Count>0){

                    <div class="shoping-cart-inner">
                        <div class="shoping-cart-table table-responsive">
                            <table class="tables table-bordered">
                                <thead>
                                    <th class="ths cart-product-remove">Remove</th>
                                    <th class="ths cart-product-image">Image</th>
                                    <th class="ths cart-product-info">Product</th>
                                    <th class="ths cart-product-price">Price</th>
                                    <th class="ths cart-product-quantity">Quantity</th>
                                    <th class="ths cart-product-subtotal">Subtotal</th>
                                </thead>
                                <tbody>
                                    @{
                                        decimal TotalPrice = 0;
                                    }
                                        @foreach (var item in Model.Products)
                                    {
                                    string cardImg = PictureHelper.GetCoverPhoto(item.CoverPhotoId, item.ProductPictures);
                                        var quantity = Model.ProductIds.Where(x => x == item.Id).Count();
                                        decimal normalPrice = item.Price - item.Discount;
                                        TotalPrice += normalPrice * quantity;
                                        <tr>
                                        <td class="cart-product-remove">
                                            <span class="btn-remove-cart" pro-id="@item.Id">x</span>
                                            </td>
                                        <td class="cart-product-image">
                                            <a asp-controller="Product" asp-action="Details" asp-route-id="@item.Id"><img width="60" src="@cardImg" alt="#"></a>
                                        </td>
                                        <td class="cart-product-info">
                                            <h4><a class="itemName" asp-controller="Product" asp-action="Details" asp-route-id="@item.Id">@item.Name</a></h4>        
                                        </td>
                                        <td class="cart-product-price">$@normalPrice</td>
                                        <td class="cart-product-quantity">
                                            <div class="cart-plus-minus" pro-id=@item.Id pro-price="@normalPrice" pro-subtotal="@(normalPrice*quantity)"> 
                                                <div class="dec qtybutton">-</div>
                                                <input type="text" value="@quantity" name="qtybutton" class="cart-plus-minus-box">
                                                <div class="inc qtybutton">+</div>
                                            </div>
                                        </td>
                                        <td class="cart-product-subtotal">$@(normalPrice*quantity)</td>
                                    </tr>   
                                    }

                           
                                </tbody>
                            </table>
                        </div>
                        <div class="shoping-cart-total mt-50">
                            <h4>Cart Totals</h4>
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>Cart Subtotal</td>
                                        <td class="totalP">@TotalPrice</td>
                                    </tr>
                        @*            <tr>
                                        <td>Shipping and Handing</td>
                                        <td>$15.00</td>
                                    </tr>
                                    <tr>
                                        <td>Vat</td>
                                        <td>$00.00</td>
                                    </tr>*@
                                    <tr>
                                      @*  <td><strong>Order Total</strong></td>
                                        <td><strong>$633.00</strong></td>*@
                                    </tr>
                                </tbody>
                            </table>
                            <div class="btn-wrapper text-right">
                                <a asp-controller="Order" asp-action="CheckOut" class="theme-btn-1 btn btn-effect-1">Proceed to checkout</a>
                            </div>
                        </div>
                    </div>
                
               
               }
                   else
                {
                    <p class="alert-danger"> Karti doldur gel...</p>
                }

               
             
                </div>
            </div>
        </div>
    </div>
    <!-- SHOPING CART AREA END -->

    <!-- FEATURE AREA START ( Feature - 3) -->
    <div class="ltn__feature-area before-bg-bottom before-bg-bottom-2 plr--5">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ltn__feature-item-box-wrap ltn__border-between-column white-bg">
                        <div class="row">
                            <div class="col-xl-3 col-md-6 col-12">
                                <div class="ltn__feature-item ltn__feature-item-8">
                                    <div class="ltn__feature-icon">
                                        <img src="Assets/img/icons/svg/4-track.svg" alt="#">
                                    </div>
                                    <div class="ltn__feature-info">
                                        <h4>Free home delivery</h4>
                                        <p>Provide free home delivery for
                                            all product over $100</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6 col-12">
                                <div class="ltn__feature-item ltn__feature-item-8">
                                    <div class="ltn__feature-icon">
                                        <img src="Assets/img/icons/svg/5-madel.svg" alt="#">
                                    </div>
                                    <div class="ltn__feature-info">
                                        <h4>Quality Products</h4>
                                        <p>We ensure the product quality
                                            that is our main goal</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6 col-12">
                                <div class="ltn__feature-item ltn__feature-item-8">
                                    <div class="ltn__feature-icon">
                                        <img src="Assets/img/icons/svg/6-return.svg" alt="#">
                                    </div>
                                    <div class="ltn__feature-info">
                                        <h4>3 Days Return</h4>
                                        <p>Return product within 3 days
                                            for any product you buy</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6 col-12">
                                <div class="ltn__feature-item ltn__feature-item-8">
                                    <div class="ltn__feature-icon">
                                        <img src="Assets/img/icons/svg/7-support.svg" alt="#">
                                    </div>
                                    <div class="ltn__feature-info">
                                        <h4>Online Support</h4>
                                        <p>We ensure the product quality
                                            that you can trust easily</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- FEATURE AREA END -->